namespace CSVQueries.Models
{
    public enum TableColumns
    {
        //excludes autogenerated Id
        FirstName=1, 
        LastName, 
        CompanyName, 
        Address, 
        City, 
        County, 
        Postal, 
        Phone1, 
        Phone2, 
        Email, 
        Web
    }
}
